version: "3.7"

services:
  app:
    build:
      context: .
    volumes:
    - ./backend:/app
    environment:
      - SECRET_KEY=khsgdfhkjlsdfksjhskdhfbjklfhdfjkkhj%%%skjdfs
      - DB_NAME=drf_angular
      - MYSQL_USER=docker-user
      - MYSQL_PASSWORD=test
    restart: on-failure
    depends_on:
      - db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:8.0
    ports:
    - "3308:3306"
    environment:
      MYSQL_DATABASE: 'drf_angular'
      MYSQL_USER: 'docker-user'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'sdfkhgsjhjshdfjsghfsjkdgfjskhushdfjsdgf'
    restart: on-failure
    volumes:
    - ./db_django:/var/lib/mysql

  web:
    image: nginx:alpine
    ports:
    - "80:80"
    links:
      - app
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
